name: 'Check User Membership'
on:
  workflow_call:
    inputs:
      command:
        required: true
        type: string
        description: 'Command to execute'
jobs:
  ai_code_reviewer:
    runs-on: [ ubuntu ]
    steps:
      - name: test
        id: check-user
        run: |        
          echo "${{ inputs.command }}"
        shell: bash
